version: "3"
services:
  prerender:
    build: .
    container_name: prerenderCacheIO
    networks:
      - default
    volumes:
      - ./cache:/srv/cache
      #- ./prerender:/srv/prerender
    ports:
      - "3000:3000"
    restart: always