version: "3"
services:
  prerender:
    # build: .
    image: rakma/prerender-cache-io:latest
    container_name: prerenderCacheIO
    networks:
      - default
    volumes:
      - ./cache:/srv/cache
      #- ./prerender:/srv/prerender
    ports:
      - "3001:3000"
    restart: always