name: Docker Image CI

on:
  push:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Get the version
      id: get_version
      run: echo VERSION=$(grep VERSION Dockerfile | cut -d '=' -f 2) >> $GITHUB_ENV

    - name: Login to DockerHub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Build and push
      id: docker_build
      uses: docker/build-push-action@v3
      with:
        context: .
        push: true
        tags: rakma/prerender-cache-io:latest, rakma/prerender-cache-io:${{ env.VERSION }}
